# Generated by Django 5.1.3 on 2024-12-01 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_deleted'),
        ('tasks', '0005_alter_taskcategories_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(related_name='tasks', through='tasks.TaskCategories', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='taskcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='taskcategories',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
